### PR TITLE
Next meeting

### PR DESCRIPTION
**Pull request by saschatimme**
@SimonDanisch Do we want to start at 18:30?
@blegat Is this description fine or do you have something more specific?

### CODE REVIEW

**Comment by daveh19** [comment]
Who's reviewing this? It looks like @SimonDanisch needs to give his ok on the time.

**Comment by SimonDanisch** [comment]
Will give it a merge once @matbesancon give some more information about JuMP talks!

**Comment by matbesancon** [comment]
so we have 2 talks already, I can present recent stuff from LightGraphs and JuliaGraphs, but it depends how much time we want to allocate to talks, what do you folks think?

**Comment by SimonDanisch** [comment]
Ah sorry, missed the second talk! Yup, shouldn't have more than two talks!

**Pull request merged**
